name: Check for dead links

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  broken-link-checker:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://beta.riskprofiler.ca
          cmd_params: --header="User-Agent:curl/7.54.0"
